/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package shortestpathwithturnrestrictions.action;

import java.awt.Cursor;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import shortestpathwithturnrestrictions.model.GraphModel;
import shortestpathwithturnrestrictions.utility.MySAXParser;

/**
 *
 * @author PprrATeekK
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    File mapDataFile;
    MySAXParser fileLoader;
    JFileChooser fchooser;
    String currentDir = null;
    BellmanFordShortestPath bfsp;
    GraphModel gModel;
    int noOfNodes;

    public MainUI() {

        initComponents();

        fchooser = new JFileChooser();
        fchooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fchooser.setDialogTitle("Select map data file");
        fchooser.setDialogType(JFileChooser.OPEN_DIALOG);

        fchooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Map data file (.osm)", "osm","OSM");
        fchooser.addChoosableFileFilter(filter);
        fchooser.setCurrentDirectory(new File("."));
        try {
            setIconImage(ImageIO.read(getClass().getResource("/shortestpathwithturnrestrictions/images/ico.png")));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        setResizable(false);
        setLocationRelativeTo(null);
        
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfFileName = new javax.swing.JTextField();
        btBrowse = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lback = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shortest Path With Turn Restrictions : Load File");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("Load data File");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 20, 380, 20);

        tfFileName.setText("Select File..");
        jPanel2.add(tfFileName);
        tfFileName.setBounds(10, 100, 187, 29);

        btBrowse.setText("Browse");
        btBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBrowseActionPerformed(evt);
            }
        });
        jPanel2.add(btBrowse);
        btBrowse.setBounds(197, 100, 80, 29);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(10, 40, 380, 10);

        lback.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shortestpathwithturnrestrictions/images/ico.png"))); // NOI18N
        lback.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lback);
        lback.setBounds(0, 0, 400, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openFile() {

        if (fchooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            mapDataFile = fchooser.getSelectedFile();
            tfFileName.setText(mapDataFile.getName());
            setCursor(Cursor.getPredefinedCursor(3));
            
            ProcessData dataProcessor =  new ProcessData(mapDataFile);
            dataProcessor.initDataModels();
            dataProcessor.drawMap();
            
            setCursor(Cursor.getDefaultCursor());

        }
        fchooser.setCurrentDirectory(fchooser.getCurrentDirectory());

    }

    

    private void btBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBrowseActionPerformed

        this.openFile();

    }//GEN-LAST:event_btBrowseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBrowse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lback;
    private javax.swing.JTextField tfFileName;
    // End of variables declaration//GEN-END:variables
}
